### PR TITLE
fix(Select): display label for empty string value

### LINKED ISSUE #490: Select: component doesn't show label if value is `empty string`
Video:
https://github.com/user-attachments/assets/10c16b7e-6d3f-42ef-94d0-2e9f150140fc

Steps:

* create Select with options:
```
const categoriesOptions = [
  { value: '', label: 'All' },
  { value: 'service', label: 'Service' },
  { value: 'billing', label: 'Billing' }
];
```
* Select first option
* It shows empty select instead of `All`

image

### PR DESCRIPTION
**Pull request by ariser**
Resolves #490 

## Why

Putting empty string as a value of `Select.Item` results in an empty Select:
image

## What

The `value` prop of `SingleSelectValue` is typed as required. Also by usage, it gets rendered only when `selectedValues` array is not empty. Thus in normal circumstances it can't be undefined or null. Seems like the emptiness check just causes the bug while not doing anything else.

### CODE REVIEW

File: src/components/Select/SingleSelectValue.tsx [hunk 1]
```diff
@@ -21,9 +21,6 @@ const SingleSelectValue = ({
   value: string;
 }) => {
   const { icon, iconDir, children, label } = valueNode ?? {};
-  if (!value) {
-    return null;
-  }
```
Comment (rndD) [inline src/components/Select/SingleSelectValue.tsx:26]: Why did we have it, tho? What was the case for this if?

Comment (ariser) [reply src/components/Select/SingleSelectValue.tsx:26]: It was initially there after the major refactoring: https://github.com/ClickHouse/click-ui/pull/137

I don't see a reason for it. The tests are green.
@vineethasok do you remember if there a specific case for this check?

Comment (vineethasok) [reply src/components/Select/SingleSelectValue.tsx:26]: This was inorder to not have any content at all when value is empty and not render the IconContainer component
If it is not causing any issue we can remove it but I added this for this reason

Comment (ariser) [reply src/components/Select/SingleSelectValue.tsx:26]: an empty string is a valid value, and we should treat it as any other string
I can keep check for undefined and null though, if you think it's needed. As of now, I don't see a way to pass these values here

Comment (ariser) [reply src/components/Select/SingleSelectValue.tsx:26]: you know what, I'll keep the check for undefined, it just makes sense

File: src/components/Select/SingleSelect.test.tsx [hunk 2]
```diff
@@ -138,6 +138,46 @@ describe("Select", () => {
...
+    expect(selectTrigger).not.toBeNull();
+    expect(selectTrigger.textContent).toBe("Select an option");
+    selectTrigger && fireEvent.click(selectTrigger);
+
+    const item = queryByText(OPTION_TEXT);
+    expect(item).not.toBeNull();
+    item && fireEvent.click(item);
+    expect(selectTrigger.textContent).toBe(OPTION_TEXT);
+  });
+
```
Comment (rndD) [inline src/components/Select/SingleSelect.test.tsx:180]: nice

**Review by rndD — APPROVED** [review]
